from django.urls import path
from .views import (
    HomeView,
    CardFaturamentoTotalAPIView,
    CardTicketMedioAPIView,
    CardVendasPorDiaHoraAPIView,
    CardProdutosMaisVendidosAPIView,
    CardProdutosMenosVendidosAPIView,
    CardProdutosMaisCustomizadosAPIView,
    CardItensComplementosMaisVendidosAPIView,
    CardTaxaCancelamentoAPIView,
    CardTaxaDescontoAPIView,
    CardPerformanceEntregaRegiaoAPIView,
    CardMixProdutosAPIView,
    CardClientesFrequentesAPIView,
    CardClientesAusentesAPIView,
    CardNovosClientesAPIView,
    CardRetencaoClientesAPIView,
    CardLifetimeValueAPIView,
    CardPerformancePorCanalAPIView,
    CardPerformancePorLojaAPIView,
    CardAnomaliasTemporaisAPIView,
    CardPrevisaoDemandaAPIView,
    CardAnalysisAPIView,
    ChartAnalysisAPIView,
    CardProdutoSazonalAPIView,
    CardCrescimentoLojaAPIView,
    CardAnomaliasOperacionaisAPIView,
    DashboardLayoutAPIView,
    SalesMapView,
    RecentSalesAPIView,
    CalendarView,
    CardComplementosMaisAdicionadosAPIView,
    CardComplementosMaisRemovidosAPIView,
    CardProdutosComItensMaisRemovidosAPIView,
    LojasListAPIView,
)



urlpatterns = [
    path('api/card-complementos-mais-adicionados/', CardComplementosMaisAdicionadosAPIView.as_view(), name='card-complementos-mais-adicionados'),
    path('api/card-itens-complementos-mais-vendidos/', CardItensComplementosMaisVendidosAPIView.as_view(), name='card-itens-complementos-mais-vendidos'),
    path('api/card-complementos-mais-removidos/', CardComplementosMaisRemovidosAPIView.as_view(), name='card-complementos-mais-removidos'),
    path('api/card-produtos-com-itens-mais-removidos/', CardProdutosComItensMaisRemovidosAPIView.as_view(), name='card-produtos-com-itens-mais-removidos'),
    path('home/', HomeView.as_view(), name='home'),
    path('map/', SalesMapView.as_view(), name='sales-map'),
    path('calendar/', CalendarView.as_view(), name='calendar'),

    # 20 endpoints dos cards do CARD_IDEAS.md
    path('api/card-faturamento-total/', CardFaturamentoTotalAPIView.as_view(), name='card-faturamento-total'),
    path('api/card-ticket-medio/', CardTicketMedioAPIView.as_view(), name='card-ticket-medio'),
    path('api/card-vendas-por-dia-hora/', CardVendasPorDiaHoraAPIView.as_view(), name='card-vendas-por-dia-hora'),
    path('api/card-produtos-mais-vendidos/', CardProdutosMaisVendidosAPIView.as_view(), name='card-produtos-mais-vendidos'),
    path('api/card-produtos-menos-vendidos/', CardProdutosMenosVendidosAPIView.as_view(), name='card-produtos-menos-vendidos'),
    path('api/card-produtos-mais-customizados/', CardProdutosMaisCustomizadosAPIView.as_view(), name='card-produtos-mais-customizados'),
    path('api/card-itens-complementos-mais-vendidos/', CardItensComplementosMaisVendidosAPIView.as_view(), name='card-itens-complementos-mais-vendidos'),
    path('api/card-taxa-cancelamento/', CardTaxaCancelamentoAPIView.as_view(), name='card-taxa-cancelamento'),
    path('api/card-taxa-desconto/', CardTaxaDescontoAPIView.as_view(), name='card-taxa-desconto'),
    path('api/card-performance-entrega-regiao/', CardPerformanceEntregaRegiaoAPIView.as_view(), name='card-performance-entrega-regiao'),
    path('api/card-mix-produtos/', CardMixProdutosAPIView.as_view(), name='card-mix-produtos'),
    path('api/card-clientes-frequentes/', CardClientesFrequentesAPIView.as_view(), name='card-clientes-frequentes'),
    path('api/card-clientes-ausentes/', CardClientesAusentesAPIView.as_view(), name='card-clientes-ausentes'),
    path('api/card-novos-clientes/', CardNovosClientesAPIView.as_view(), name='card-novos-clientes'),
    path('api/card-retencao-clientes/', CardRetencaoClientesAPIView.as_view(), name='card-retencao-clientes'),
    path('api/card-lifetime-value/', CardLifetimeValueAPIView.as_view(), name='card-lifetime-value'),
    path('api/card-performance-por-canal/', CardPerformancePorCanalAPIView.as_view(), name='card-performance-por-canal'),
    path('api/card-performance-por-loja/', CardPerformancePorLojaAPIView.as_view(), name='card-performance-por-loja'),
    path('api/card-anomalias-temporais/', CardAnomaliasTemporaisAPIView.as_view(), name='card-anomalias-temporais'),
    path('api/card-previsao-demanda/', CardPrevisaoDemandaAPIView.as_view(), name='card-previsao-demanda'),
    # Endpoints agregados/insights
    path('api/card-produto-sazonal/', CardProdutoSazonalAPIView.as_view(), name='card-produto-sazonal'),
    path('api/card-crescimento-loja/', CardCrescimentoLojaAPIView.as_view(), name='card-crescimento-loja'),
    # 'card-mix-produtos-global' foi removido; use 'card-mix-produtos' (original antes da seção de insights)
    path('api/card-anomalias-operacionais/', CardAnomaliasOperacionaisAPIView.as_view(), name='card-anomalias-operacionais'),
    path('api/card-analysis/', CardAnalysisAPIView.as_view(), name='card-analysis'),
    path('api/chart-analysis/', ChartAnalysisAPIView.as_view(), name='chart-analysis'),
    path('api/dashboard-layout/', DashboardLayoutAPIView.as_view(), name='dashboard-layout'),
    path('api/recent-sales/', RecentSalesAPIView.as_view(), name='recent-sales'),
    path('api/lojas/', LojasListAPIView.as_view(), name='lojas-list'),
]

